#! /bin/bash

# This is a `bash` include file, so bash escaping may be necessary


# If a duplicate domains exist, "Y" means retain the ICANN records & drop the Handshake ones
# anything other than "Y" and Handshake records are prioritised
priority_icann="Y"


# IP Address to query for Handshake ROOT SOA Serial
# i.e `hsd` server address `--ns-hotst <addr>`
hsd_server_addr="127.0.0.9"


# Path to the HSD-RPC client
hsd_rpc="/opt/hs-client/bin/hsd-rpc"


# algorithm to use to sign the ROOT zone
signing_algorithm="ECDSAP384SHA384"


# Addresses in this prefix are used so `bind` can talk to itself
# the value doesn't really matter, so long as your not using it for anything else
bind_local_prefix="127.9.0"


# IP Addresses for `bind` to run your required service on
# if you don't want any of these services available externally, use a 127.0.0.0/8 address
# NOTE: Unlike most Linux apps, `bind` can't use an IP unless it has been explicitly assigned to an interface
bind_recusive_addr="192.168.1.181"
bind_slave_addr="192.168.1.182"
bind_mirror_addr="192.168.1.183"
